### PR TITLE
7.4

### LINKED ISSUE #16: Update to a modern PRAW version
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Hey @djsutherland , sorry to nag, but the feedstock is well over a year out of date, with 7 PRAW releases since it was last updated (7.3.0 being the latest), a PRAW 8.0 release forthcoming, and imminent Reddit API changes meaning that old PRAW versions will not be usable with current Reddit (particularly the refresh token handling changes introduced in 7.2.0, in response to my and others' requests, to handle the corresponding changes on Reddit's side). I see the build started failing with the 7.1.1 autotick, but its been so long since those PRs were opened that I can't see the build log anymore, and they are well out of date in any case. I've had to update my applications to be compatible with those changes, which means they require PRAW <7.2.0, and have to rely on pip-installed PRAW.

Is there any change of upgrading to a modern PRAW version (at least 7.2.0+) by someone familiar with the feedstock? If you're too busy and no one else is available, I'm willing to give it a shot myself (I've skimmed the docs but I don't have a lot of practical experience with CF package maintenance) so long as my PR will be reviewed. Let me know, thanks!

### PR DESCRIPTION
**Pull request by djsutherland**
Long-overdue update to a recent version.

Closes #12, closes #13, closes #14, closes #15, closes #16

### CODE REVIEW

**Comment by djsutherland** [comment]
@CAM-Gerlach re: https://github.com/conda-forge/praw-feedstock/pull/15#issuecomment-774852467

I finally got around to updating praw and prawcore; sorry for the absurd delay here. If you'd like to add yourself on as a maintainer, I'd happily accept that; I don't use praw regularly anymore, and have not been keeping up with my conda-forge maintainerships in general.

**Comment by djsutherland** [comment]
(New `prawcore` just hasn't hit the cache yet; will rerun later.)

**Comment by CAM-Gerlach** [comment]
Hey @djsutherland , thanks so much for taking care of this. I'm happy to go ahead and add myself as well, and let me know if I can be of further help on this one. Thanks!

**Comment by CAM-Gerlach** [comment]
This should close #16 as well, FYI

**Comment by CAM-Gerlach** [comment]
Thanks @djsutherland !

**Pull request merged**
